### PR TITLE
Allow creating multiple backports from one pull request

### LINKED ISSUE #17: Creating multiple backports at once
I just discovered this app and already love it.

It seems that currently it's only possible to do a single backport. We maintain multiple stable branches but specifying multiple labels only opens one backport. Would it be possible to have several backports ( like `backport release-3_4` and `backport release-3_6`)?

### PR DESCRIPTION
**Pull request by m-kuhn**
Fix #17 

Disclaimer: I have never written TypeScript before and have used the github online editor. Needs careful review!

### CODE REVIEW

**Comment by m-kuhn** [comment]
Apparently when backporting to multiple branches, there is only one comment about a backport failure, even if multiple backports fail. This makes it hard to quickly see which backports need to be done manually.

@tibdex  do you have an idea why this is? Some throttling on github side maybe?

**Comment by tibdex** [comment]
It's because I use `p-series`:

https://github.com/tibdex/backport/blob/35fd5c5c293fa0ea4f71e838aeca43309a258df0/src/backport.ts#L137-L141

And [its doc](https://www.npmjs.com/package/p-series#pseriestasks) says:

> Returns a Promise that is fulfilled when all promises returned from calling the functions in tasks are fulfilled, or rejects if any of the promises reject. The fulfilled value is an Array of the fulfilled values.

It would indeed be better to try them all, even if one rebase failed.

**Comment by m-kuhn** [comment]
That sounds reasonable.
Are you aware of a better alternative? If you are able to give me an initial hint, I can try to make a pull request.

**Comment by tibdex** [comment]
Tracking this with #18, the fix should be fairly easy.

**Comment by m-kuhn** [comment]
In fact I fail to understand the documentation you cited. From what I can see it mentions the aggregated end result of the promise but doesn't talk about continuation after a rejected function. `p-all` and friends docs look very similar to me. It's likely related to the fact that the whole concept and terminology with "promises" is new to me.

**Comment by tibdex** [comment]
You can see the fix in https://github.com/tibdex/backport/commit/c252bc6349b321ed8f9cd96641b1cea1f6ec60fe, tell me if you don't understand something ;)

**Pull request merged**
